resources:
  - ./nginx
  - ./whoami
  - ./external-secrets
  #- ./n8n/app
  - ./openebs
  - ./homepage
  - ./monitoring 
  - ./pihole
  - ./wallabag
  - ./linkding
  - ./postgresql 
  - ./cloudnative-pg
  - ./pgadmin 
  - ./1password 
  - ./argocd
  #- ./n8n
  #- ./monitoring-system
  